dist: trusty
sudo: required
language: php
php:
  - '7.1'
  
services:
  - mysql
  - redis-server
  - couchdb
  
before_install:  
  - mysql -e 'CREATE DATABASE IF NOT EXISTS _deepqueue_test_;'
  
before_script:
  - composer install --prefer-source --no-interaction
  
script:
  - composer test-cover
  - php vendor/bin/coveralls